### ISSUE TITLE
Project roadmap link broken

### ISSUE THREAD

**Issue by bholagabbar** [SoftwareEngineeringDaily/softwareengineeringdaily.github.io#7]
The link to the GitHub project roadmap is https://github.com/orgs/SoftwareEngineeringDaily/projects/1 which is broken. The link can be found *Look at the “brainstorming” section of our roadmap. This is where we explore feature ideas.* On the homepage. I'm not quite sure what the link is so haven't issued a PR

@crablar

**Comment by crablar** [comment]
Fixed! Now points to https://github.com/SoftwareEngineeringDaily/softwareengineeringdaily.github.io/projects/1
